name: Repo Dispatch Action

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make a simple curl request to cross-repo-builds repo
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/tausif-dukaan/cross-repo-builds/dispatches \
          -d '{"event_type":"cross_repo_dispatch_event"}'
          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~ hello world ~~~~~~~~~~~~~~~~~~~~~~~~~~"
          