name: Repo Dispatch Action

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make a simple curl request
        run: |
          curl https://www.keycdn.com
          echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
          curl https://www.google.com
          echo "##################################"
          curl https://www.twitter.com
          echo "**********************************"